/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mqt_cmakedemo2_BlurUtils */

#ifndef _Included_com_mqt_cmakedemo2_BlurUtils
#define _Included_com_mqt_cmakedemo2_BlurUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mqt_cmakedemo2_BlurUtils
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_mqt_cmakedemo2_BlurUtils_blurPixels
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_mqt_cmakedemo2_BlurUtils
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_mqt_cmakedemo2_BlurUtils_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
